steps:
# SSH into GCP VM and update code from the Git repository
- id: 'GitCheckout'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'cd ~/SAVE-SONE && git pull'

# SSH into GCP VM and install Python dependencies
- id: 'InstallDependencies'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'cd ~/SAVE-SONE && python3 -m venv myenv && source myenv/bin/activate && pip install -r requirements.txt'

# SSH into GCP VM and update everything
- id: 'UpdateEverything'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'sudo apt-get update -y && sudo apt-get full-upgrade -y && sudo apt-get autoremove -y && sudo apt-get clean -y && sudo apt-get autoclean -y'

# SSH into GCP VM and start Flask application
- id: 'StartFlaskApplication'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'cd ~/SAVE-SONE && python3 -m venv myenv && source myenv/bin/activate && gunicorn -bind 0.0.0.0:5000 wsgi:app'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET