steps:
# SSH into GCP VM and clear whole web before update
- id: 'ClearWebDirectory'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'rm -rf ~/SAVE-SONE'

# SSH into GCP VM and get code from the Git repository
- id: 'GitCheckout'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'cd ~/ && git clone --single-branch --branch main https://github.com/PKForm/SAVE-SONE.git SAVE-SONE'

# SSH into GCP VM and install Python dependencies
- id: 'InstallDependencies'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'cd ~/SAVE-SONE && python3 -m venv myenv && source myenv/bin/activate && pip install -r requirements.txt && deactivate'

# SSH into GCP VM and update everything
- id: 'UpdateEverything'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean -y && sudo apt autoclean -y'

# SSH into GCP VM and start Flask application
- id: 'StartFlaskApplication'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh --zone us-west1-c --project dauntless-glow-412512 g6451500315@save-sone-server --command 'cd ~/SAVE-SONE && python3 -m venv myenv && source myenv/bin/activate && gunicorn -b 0.0.0.0:5000 app:app && deactivate'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET