steps:
# Clean up the contents of the 'app' directory
- id: 'Cleanup'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'rm -rf ~/app/*'

# Check out the code from the Git repository
- id: 'GitCheckout'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch', 'main', 'https://github.com/PKForm/SAVE-SONE.git', '~/app']

# Change directory to the cloned repository
- id: 'GitToCloned'
  name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'dfeb204a35ea466162b0874122355bc96efa1c13']
  dir: '~/app'

# Install Python dependencies
- id: 'InstallDependencies'
  name: python
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt']

# Copy files to GCP VM (assuming SSH key authentication)
- id: 'CopyFilesToVM'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--recurse', '--quiet', '--zone', 'us-west1-c', '~/app', 'g6451500315@save-sone-server:~/app']

# SSH into GCP VM and deploy application
- id: 'SSHIntoVMAndDeploy'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', '--zone', 'us-west1-c', 'g6451500315@save-sone-server:~/app', '--command', 'cd ~/app && ./deploy.sh']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET